[
	{
		name:"服装鞋包",items:[
			{name:"男装",items:[
				{name:"背心/马甲"},
				{name:"衬衫"},
				{name:"风衣"},
				{name:"工装制服"},
				{name:"夹克"},
				{name:"棉裤"},
				{name:"毛呢大衣"},
				{name:"棉衣"},
				{name:"民族服装"},
				{name:"牛仔裤"},
				{name:"Polo衫"},
				{name:"皮裤"},
				{name:"皮衣"},
				{name:"T恤"},
				{name:"卫衣"},
				{name:"休闲裤"},
				{name:"西服"},
				{name:"西裤"},
				{name:"西服套装"}
			]},
			{name:"流行男鞋",items:[
				{name:"低帮鞋"},
				{name:"帆布鞋"},
				{name:"高帮鞋"},
				{name:"凉鞋"},
				{name:"拖鞋"},
				{name:"靴子"},
				{name:"雨鞋"}
			]},
			{name:"女装/女士精品"},
			{name:"女鞋"}
		]
	},{
		name:"手机数码",items:[
			{name:"国货精品数码",items:[
				{name:"国货精品笔记本"},
				{name:"国货精品手机"}
			]},
			{name:"数码相机/单反相机/摄像机",items:[
				{name:"单反镜头"},
				{name:"单电微单"},
				{name:"胶卷相机"},
				{name:"普通数码相机"},
				{name:"数码摄像机"},
				{name:"专业数码单反"}
			]},
			{name:"MP3/MP4/MP5/IPOD/录音笔"},
			{name:"笔记本电脑"},
			{name:"平板电脑"}
		]
	},{
		
	}
]